---
version: "2"

services:
  narou:
    image: my/narou-rpi
    container_name: narou
    environment:
      - PUID=puid
      - PGID=pgid
      - TZ=Asia/Tokyo
    command: ["narou", "web", "-np", "33000"]
    volumes:
      - /path/to/narou:/novel:cached
    # tty: true
    # stdin_open: true
    ports:
      - 33000:33000
      - 33001:33001
    restart: always